<section id="donate_mmo_checkout">
    <div class="page-title">
        <h2>Pay with Solana (MMOCoin)</h2>
    </div>

    <div class="checkout-box text-center" style="text-align:center; margin: 30px auto; max-width: 400px; background: #1a1e24; padding: 25px; border-radius: 12px; border: 1px solid #333;">
        <h3>{$package.price} MMOCoin</h3>
        <p style="color: #aaa; font-size: 14px; margin-bottom: 20px;">Scan this QR code with your Phantom or Solflare mobile app.</p>

        <!-- Container for the QR Code generated by JS -->
        <div id="solana-qr-container" style="background: white; padding: 15px; border-radius: 8px; display: inline-block;"></div>

        <div style="margin-top: 20px; font-family: monospace; font-size: 12px; color: #777; word-break: break-all;">
            <strong>Amount:</strong> {$package.price} MMOCoin<br>
            <strong>Reference:</strong> {$reference}
        </div>
        
        <p id="payment-status" style="margin-top: 20px; font-weight: bold; color: orange;">
            <i class="fa fa-spinner fa-spin"></i> Awaiting payment...
        </p>

        <!-- Hidden inputs for JS to use -->
        <input type="hidden" id="solana-pay-url" value="{$solana_pay_url}">
        <input type="hidden" id="verification-url" value="{$url}donate_mmo/verify_payment/{$reference}">
    </div>
</section>

<!-- Include required libraries for QR generation -->
<!-- You can put this in the JS file or load externally, but doing it here ensures it runs for the module -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
